[2025-06-23 07:11:38,662] INFO main:195 - Running step: step03_store_vectors
[2025-06-23 07:11:38,662] INFO main:196 - Input file: ATMEGA2560.txt
[2025-06-23 07:11:38,663] INFO main:197 - Query: None
[2025-06-23 07:11:38,663] INFO main:198 - Config loaded from: config.json
[2025-06-23 07:11:38,663] INFO main:47 - Ensured directory exists: data\raw_input
[2025-06-23 07:11:38,664] INFO main:47 - Ensured directory exists: data\cleaned_text
[2025-06-23 07:11:38,664] INFO main:47 - Ensured directory exists: data\embeddings
[2025-06-23 07:11:38,665] INFO main:47 - Ensured directory exists: data\vectordb
[2025-06-23 07:11:38,674] INFO main:79 - [Step 03] Vector storage started.
[2025-06-23 07:11:38,675] INFO main:83 - Deleting existing vectordb
[2025-06-23 07:11:38,677] ERROR utilities:37 - Error deleting directory data/vectordb: [WinError 5] Access is denied: 'data/vectordb'
[2025-06-23 07:11:38,678] INFO embedding_loader:26 - ðŸ”ƒ Starting vector store creation...
[2025-06-23 07:11:38,775] DEBUG config:359 - Starting component System
[2025-06-23 07:11:38,775] DEBUG config:359 - Starting component Posthog
[2025-06-23 07:11:38,841] ERROR main:214 - Pipeline crashed during execution.
Traceback (most recent call last):
  File "C:\Users\Helen Zegarra\OneDrive\Documents\Desktop\AI class projects\iot-rag\main.py", line 211, in main
    steps[args.step](args)
  File "C:\Users\Helen Zegarra\OneDrive\Documents\Desktop\AI class projects\iot-rag\main.py", line 98, in step03_store_vectors
    loader.process_files()
  File "C:\Users\Helen Zegarra\OneDrive\Documents\Desktop\AI class projects\iot-rag\classes\embedding_loader.py", line 54, in process_files
    embeddings = embedding_data.get("embeddings", [])
AttributeError: 'list' object has no attribute 'get'
[2025-06-23 07:11:38,842] INFO main:216 - RAG pipeline done
